### ISSUE TITLE
Number of values count in labeled_anomalies.csv is off

### ISSUE THREAD

**Issue by ConnorWasHere** [khundman/telemanom#1]
There is a slight difference between the amount of records in the num_values column and the actual amount of records present. For instance P-1 is shown to have 8321 records in labeled_anomalies.csv, but the data itself has 8505 records.

**Comment by miazoin** [comment]
Viewed the same issue.

**Comment by khundman** [comment]
Fixed in https://github.com/khundman/telemanom/commit/3a18a417f9275a26d936b828104337e51f97e0b8. Thanks!
