### ISSUE TITLE
Telemanom availability for notebook users

### ISSUE THREAD

**Issue by CaptainOrange88** [khundman/telemanom#13]
Hello,

Great tool I may say. Still I'm trying to make this available for multiple notebook users but failing.
How can I link this tool to a Jupyterhub session?
Kindly offer some notes on the matter.

Best!

**Comment by khundman** [comment]
Thanks for the note. The notebook is only provided to view result plots, but this can be done in Jhub by uploading the notebook and associated data files using the same structure as in the current repo. To run training/inference you would have to move `run.py` into a notebook maintaining the existing structure (and move it all to Jhub).
