### ISSUE TITLE
Question about selection of the telemetry variable

### ISSUE THREAD

**Issue by WangMinhu** [khundman/telemanom#16]
First of all, thank you for your excellent paper and source code! 

I notice that in your algorithm design and implement, only a feature was selected as the telemetry variable. In paper, such a choice was explained as 

>  Since our aim is to predict telemetry values for a single channel we consider the situation where d = 1.

In source code, it seemed that the first feature was selected as the telemetry variable for all channels.

` y = data[:,-config.n_predictions:,0] #telemetry value is at position 0`

So **I wonder whether the same feature was selected as the telemetry one for all channels or the orders of features were different for different channels and the telemetry variable was set as the first feature?**

What's more, could you give some general advice on how to choose a good telemetry variable? 
I would appreciate if you could reply.

**Comment by kidluo** [comment]
chinglish

**Comment by khundman** [comment]
Thanks for the note!

The individual telemetry channel was always in the first position in the arrays for this work and the ordering was consistent. 

I'm not sure what you mean by "choosing a good telemetry variable"?
