### ISSUE TITLE
Question about errors.py

### ISSUE THREAD

**Issue by lshhhhh** [khundman/telemanom#2]
Hi, I found something wrong while running the code.
I wonder if it is ```not x + b >= len(e_s)``` instead of ```not x + b > len(e_s)``` in
https://github.com/khundman/telemanom/blob/master/telemanom/errors.py#L223, because i_anom(x+b) means index of error.

**Comment by khundman** [comment]
Thanks! Fixed in https://github.com/khundman/telemanom/commit/3a18a417f9275a26d936b828104337e51f97e0b8.
