### ISSUE TITLE
Asking for overfitting issue

### ISSUE THREAD

**Issue by Euicheon** [khundman/telemanom#25]
I'm trying to apply this model on my data. (minute data)

My data shows a trend of "one day"(1440 minutes), and I trained with 21 days of training data before running the test. "l_s" is set to 1440 and "n_prediction" is set to 10. However, the y_hat graph was drawn in the form of lagging, just follow right before value.

Please advise how I can solve the problem.

PS. I tried various parameter settings and added LSTM layers for the model.. However I haven't found right model yet.

**Comment by khundman** [comment]
You may want to try predicting further in the future to discourage the model from repeating recent values. Some options would be to use a discrete value `n` minutes ahead as `y` or a longer predicted sequence of values. See #24

**Comment by Euicheon** [comment]
Thank you for answer me. It is little bit hard to avoid overfitting. I should try denoising method on my data.
