### ISSUE TITLE
Does the data only have categorical inputs?

### ISSUE THREAD

**Issue by francisduan** [khundman/telemanom#35]
I have noticed that most of the input entries are zero, and I am wondering if the attached dataset has any numerical inputs (sensor readings, etc.)? If there is, are you using them with one-hot encodings directly?

**Comment by khundman** [comment]
Yes the telemetry channel's recent history is included. See the 'Data' section in the Readme for more details.

**Comment by francisduan** [comment]
Hi thanks for the reply. But my question was whether you are using numerical values and one-hot encoding values together? 

Does it make sense to separate the two? Since numerical values might have very different latent information compared with categorical values

**Comment by khundman** [comment]
Yes they are used together, this is shown here: 

![image](https://user-images.githubusercontent.com/5148804/77259020-784f5200-6c4c-11ea-97a8-306bc51886ad.png)

There's more discussion in my response to Q3 in #8 as well as in the [paper](https://arxiv.org/pdf/1802.04431.pdf).

It definitely could make sense to separate the two.

**Comment by francisduan** [comment]
Thanks a lot for this, sorry I did not realize the original y is also an input. 

So the algorithm is transforming a Multivariate time series (MTS) into a univariate one (output y hat), with the target y included in the MTS as well. Is this correct?

**Comment by khundman** [comment]
This is explained in the "Methods" section in the paper:

![image](https://user-images.githubusercontent.com/5148804/77259354-ccf3cc80-6c4e-11ea-98c0-90fbbf481c8b.png)

Prior values of `y` are inputs for the prediction of the current `y` value.

**Comment by francisduan** [comment]
ok thank you
