### ISSUE TITLE
Use for Univariate Time Series

### ISSUE THREAD

**Issue by ivanokeeffe** [khundman/telemanom#37]
Hi, before I dive into trying to use this implementation, I am wondering if you can use these methods for univariate time-series numerical data?

**Comment by khundman** [comment]
Yes you could

**Comment by changqa** [comment]
> Hi, before I dive into trying to use this implementation, I am wondering if you can use these methods for univariate time-series numerical data?

hi! I am also trying to use this for univariate time-series numerical data, did you success? Would you mind sharing your configuration? Thanks

**Comment by Purav-Zumkhawala** [comment]
I do not have any channel data so how would I go on implementing for my own dataset as predicting requires channel id.
