### ISSUE TITLE
Unsupervised Anomaly Detection

### ISSUE THREAD

**Issue by mkemaltas** [khundman/telemanom#38]
There was a branch for unsupervised anomaly detection a while ago when I last checked. Is that branch removed, or does telemanom still support unsupervised anomaly detection?

**Comment by khundman** [comment]
This functionality was merged into `master`.

Just run without passing a set of labels to find anomalies on your data, i.e.: 

```python
from telemanom.detector import Detector

if __name__ == '__main__':
    detector = Detector(labels_path=None)
    detector.run()
```

**Comment by mkemaltas** [comment]
Thanks a lot!
