### ISSUE TITLE
Problem about the dataset dimensions

### ISSUE THREAD

**Issue by JinchuanZ** [khundman/telemanom#43]
Dear Author，

As you said, the data in column（dimension）0 is real telemetry data, so what role does the data from other dimensions play in this project, and do they influence the results（performance）? Can I keep only the 0 th dimension of real telemetry data for my training？

**Comment by khundman** [comment]
The other dimensions represent one hot-encoded command data, which affects telemetry behavior. We didn't do experiments with only the telemetry channels in the 0th dimension, but it would be interesting to see that comparison.
