### ISSUE TITLE
Cannot run example.py because of lack of dataset

### ISSUE THREAD

**Issue by striverr** [khundman/telemanom#47]
I'm sorry that when I run example.py I find that I don't have the "existing dataset" ,can you tell me where is the corresponding file that is needed?

**Comment by sarahmish** [comment]
@striverr you can find the command in the [README](https://github.com/khundman/telemanom#to-run-with-local-or-virtual-environment) which you should unzip in the root folder of the repo.
```python3
curl -O https://s3-us-west-2.amazonaws.com/telemanom/data.zip && unzip data.zip && rm data.zip
```
if you want to do it manually, just download the compressed file `https://s3-us-west-2.amazonaws.com/telemanom/data.zip` then unzip it using any app.

**Comment by striverr** [comment]
> @striverr you can find the command in the [README](https://github.com/khundman/telemanom#to-run-with-local-or-virtual-environment) which you should unzip in the root folder of the repo.
> 
> ```python
> curl -O https://s3-us-west-2.amazonaws.com/telemanom/data.zip && unzip data.zip && rm data.zip
> ```
> 
> if you want to do it manually, just download the compressed file `https://s3-us-west-2.amazonaws.com/telemanom/data.zip` then unzip it using any app.

**Comment by striverr** [comment]
I'm new to github and I don't know how to respond the comment above. So I wish what he can see my thanks here!!!! I solved this problem with your help!!!
