### ISSUE TITLE
co-relation

### ISSUE THREAD

**Issue by bappctl** [khundman/telemanom#52]
How the multi variate co-relation between channels achieved? Thanks

**Comment by khundman** [comment]
This is described in the depth in the [paper](https://arxiv.org/pdf/1802.04431.pdf). If you have more detailed questions or if there are parts that aren't clear please reference them specifically.

**Comment by bappctl** [comment]
thank you

**Comment by khundman** [comment]
No, contextual refers to other nearby P-1 channel values. Please see the definition of a "contextual" anomaly in first paragraph of section 2 in the [paper](https://arxiv.org/pdf/1802.04431.pdf): 

"...contextual anomalies are single values that do not fall within low-density regions yet are anomalous with
regard to local values."
