### ISSUE TITLE
Problem with the simple example

### ISSUE THREAD

**Issue by terry07** [khundman/telemanom#56]
Could anyone help with the next error on the simple example:

ValueError: Run ID 2018-05-19_15.00.10 is not valid. If loading prior models or predictions, must provide valid ID.

Thanks for your time.

**Comment by khundman** [comment]
@terry07 each time you generate predictions, a `run_id` is created. In `config.yaml`, the default `run_id` corresponds to the experiment and data detailed in the paper (predictions are pre-generated). If you want to recreate anomaly results from the paper and use this `run_id` make sure you pull down the data corresponding to this run (see [here](https://github.com/khundman/telemanom#to-run-with-local-or-virtual-environment)). Or if you are training your own models and generating different predictions, change the `run_id` to match the `run_id` for that output.
