### ISSUE TITLE
point anomalies and `error_buffer`

### ISSUE THREAD

**Issue by severous** [khundman/telemanom#59]
Thanks for your brilliant work.  I am confused about some questions. 
- It seems that all the anomalies in the smap dataset occur consecutively. I would like to know how you define point anomalies
- I would like to know the purpose of setting the parameter `error_buffer`
```python
i_anom = np.sort(np.concatenate((i_anom,
                                            np.array([i+buffer for i in i_anom])
                                             .flatten(),
                                            np.array([i-buffer for i in i_anom])
                                             .flatten())))
```

**Comment by khundman** [comment]
This is explained in section 4.1 of the paper:

"Predicted anomalous regions are also slightly expanded to facilitate the combining of anomalous regions in close proximity – regions that overlap or touch after expansion are combined into a single region to account for situations where multiple anomalous regions represent a single event."

This also answers your second question, and take a look at #58 for more intuition of the `error_buffer` parameter.
