### ISSUE TITLE
Does Channel mean the first column in the dataset 

### ISSUE THREAD

**Issue by sada-narayanappa** [khundman/telemanom#63]
In section 3.1 the last paragraph, I read

“A prediction length lp then determines the number of steps ahead to predict, where the number of dimensions d being predicted is 1 ≤ d ≤ m. Since our aim is to predict telemetry values for a single channel we consider the ...“

I think the word “channel” is overloaded – if I were to consider channel as group of sensors, the above highlighted phrase is meant to say “single sensor” I think. Because predict channel means, predicting all the dimensions.
OR

Should I assume the first column is the channel and remaining columns are command inputs or status outputs and "predicting channel" means predicting the first column - I think it is the latter - but wanted to confirm.

**Comment by sada-narayanappa** [comment]
I think the channel is the first column in the corresponding dataset. All others are some form of categorical one-hot encoded as described in the paper ~ It would be good to find some open telemetry datasets

**Comment by khundman** [comment]
A channel only represents one dimension of telemetry values (the first dimension) for each model. The next sentence after the one you quoted states:

> Since our aim is to predict telemetry values for a single channel we consider the situation where `d = 1`. 

Other dimensions in each `.npy` file are the same set of one-hot encoded commanding information append to each channel's one-dimensional channel values.
